import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import wall from "../../public/wall.png";
import glass from "../../public/glass.png";
import classNames from "classnames";

const noto = Noto_Serif({ subsets: ["latin"], variable: "--font-noto" });
const cav = Caveat({ subsets: ["latin"], variable: "--font-cav" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(noto.className, cav.variable)}>
        {children}
      </body>
    </html>
  );
}
